# @format
branches:
  only:
    - master

os: linux
dist: focal
language: node_js
node_js:
  - 14

before_install:
  - npm i -g npm@7

jobs:
  include:
    - stage: Checking dependencies
      script:
        - npm --version
    - stage: DemoFull
      script:
        - npm install

